INSERT INTO ingredients (name, measurementunit) VALUES ('Beef Patty', 'grams');
INSERT INTO ingredients (name, measurementunit) VALUES ('Cheese', 'slices');
INSERT INTO ingredients (name, measurementunit) VALUES ('Lettuce', 'grams');
INSERT INTO ingredients (name, measurementunit) VALUES ('Tomato', 'slices');
INSERT INTO ingredients (name, measurementunit) VALUES ('Onion', 'slices');
INSERT INTO ingredients (name, measurementunit) VALUES ('Pickles', 'slices');
INSERT INTO ingredients (name, measurementunit) VALUES ('Bacon', 'slices');
INSERT INTO ingredients (name, measurementunit) VALUES ('Chicken Breast', 'pieces');
INSERT INTO ingredients (name, measurementunit) VALUES ('Crispy Chicken Tender', 'pieces');
INSERT INTO ingredients (name, measurementunit) VALUES ('Steak Finger', 'pieces');
INSERT INTO ingredients (name, measurementunit) VALUES ('Burger Buns', 'pieces');
INSERT INTO ingredients (name, measurementunit) VALUES ('Sandwich Buns', 'pieces');
INSERT INTO ingredients (name, measurementunit) VALUES ('Rev Sauce', 'grams');
INSERT INTO ingredients (name, measurementunit) VALUES ('Fries', 'grams');
INSERT INTO ingredients (name, measurementunit) VALUES ('Onion Rings', 'grams');
INSERT INTO ingredients (name, measurementunit) VALUES ('Tator Tots', 'grams');
INSERT INTO ingredients (name, measurementunit) VALUES ('Sweet Potato Fries', 'grams');
INSERT INTO ingredients (name, measurementunit) VALUES ('Chili', 'grams');
INSERT INTO ingredients (name, measurementunit) VALUES ('Ice Cream', 'scoops');
INSERT INTO ingredients (name, measurementunit) VALUES ('Milkshake Base', 'ml');
INSERT INTO ingredients (name, measurementunit) VALUES ('Chocolate Syrup', 'grams');
INSERT INTO ingredients (name, measurementunit) VALUES ('Vanilla Flavor', 'ml');
INSERT INTO ingredients (name, measurementunit) VALUES ('Brownie', 'pieces');
INSERT INTO ingredients (name, measurementunit) VALUES ('Chocolate Chip Cookie', 'pieces');
INSERT INTO ingredients (name, measurementunit) VALUES ('Soda', 'ml');
INSERT INTO ingredients (name, measurementunit) VALUES ('Water', 'bottles');
INSERT INTO ingredients (name, measurementunit) VALUES ('Sugar', 'grams');
INSERT INTO ingredients (name, measurementunit) VALUES ('Fountain Drink Cup', 'pieces');
INSERT INTO ingredients (name, measurementunit) VALUES ('Napkins', 'pieces');
INSERT INTO ingredients (name, measurementunit) VALUES ('Forks', 'pieces');
INSERT INTO ingredients (name, measurementunit) VALUES ('Spoons', 'pieces');
INSERT INTO ingredients (name, measurementunit) VALUES ('Straws', 'pieces');
INSERT INTO ingredients (name, measurementunit) VALUES ('Order Box', 'pieces');
INSERT INTO ingredients (name, measurementunit) VALUES ('Hot Sauce', 'grams');
INSERT INTO ingredients (name, measurementunit) VALUES ('Grilled Chicken Tender', 'pieces');
INSERT INTO ingredients (name, measurementunit) VALUES ('Fork', 'pieces');
INSERT INTO ingredients (name, measurementunit) VALUES ('Spoon', 'pieces');
INSERT INTO ingredients (name, measurementunit) VALUES ('Knife', 'pieces');
INSERT INTO ingredients (name, measurementunit) VALUES ('Water Cup', 'pieces');
INSERT INTO ingredients (name, measurementunit) VALUES ('Napkin', 'pieces');
INSERT INTO ingredients (name, measurementunit) VALUES ('To Go Box', 'pieces');
INSERT INTO ingredients (name, measurementunit) VALUES ('Bag', 'pieces');