INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Rev''s Burger Meal', 7.49, TRUE, 1, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Double Stack Cheese Burger Meal', 10.69, TRUE, 1, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Classic Burger Meal', 7.39, TRUE, 1, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Bacon Cheeseburger Meal', 8.89, TRUE, 1, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Three Tender Basket Meal', 7.89, TRUE, 1, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Four Steak Finger Basket Meal', 8.39, TRUE, 1, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Gig ''Em Patty Melt Meal', 8.09, TRUE, 1, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Howdy Spicy Ranch Chicken Strip Sandwich Meal', 8.89, TRUE, 1, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Classic Crispy Chicken Tender Sandwich Meal', 7.69, TRUE, 1, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Classic Grilled Chicken Tender Sandwich Meal', 7.69, TRUE, 1, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Grilled Cheese Meal', 5.39, TRUE, 1, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Rev''s Burger', 5.59, TRUE, 2, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Double Stack Cheese Burger', 8.79, TRUE, 2, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Classic Burger', 5.49, TRUE, 2, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Bacon Cheeseburger', 6.99, TRUE, 2, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Three Tender Backet', 6.79, TRUE, 2, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Four Steak Finger Basket', 7.29, TRUE, 2, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Gig ''Em Patty Melt', 6.29, TRUE, 2, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Howdy Spicy Ranch Chicken Strip Sandwich', 6.99, TRUE, 2, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Classic Crispy Chicken Tender Sandwich', 5.79, TRUE, 2, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Classic Grilled Chicken Tender Sandwich', 5.79, TRUE, 2, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Grilled Cheese', 3.49, TRUE, 2, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Fries', 1.59, TRUE, 4, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Onion Rings', 1.99, TRUE, 4, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Tator Tots', 1.59, TRUE, 4, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Sweet Potato Fries', 1.99, TRUE, 4, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Chili Cheese Fries', 2.49, TRUE, 4, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Fountain Drink', 2.25, TRUE, 3, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Water Bottle', 1.85, TRUE, 3, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Vanilla Milkshake', 3.99, TRUE, 3, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Chocolate Milkshake', 3.99, TRUE, 3, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Brownie', 1.55, TRUE, 5, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Chocolate Chip Cookie', 1.65, TRUE, 5, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Double Scoop Ice Cream', 2.05, TRUE, 5, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Fork', 0.00, TRUE, 6, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Spoon', 0.00, TRUE, 6, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Knife', 0.00, TRUE, 6, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Water Cup', 0.00, TRUE, 6, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Napkin', 0.00, TRUE, 6, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('To Go Box', 0.00, TRUE, 6, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
INSERT INTO products (name, price, isactive, categoryid, imageurl) VALUES ('Bag', 0.00, TRUE, 6, 'https://s3-media0.fl.yelpcdn.com/bphoto/H22MLJCmUdfwASD5rJkDhQ/348s.jpg');
